# Generated by Django 4.0.4 on 2023-08-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.CharField(max_length=400, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.TextField(max_length=400, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='изображение')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за покупку')),
                ('date_of_add', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('date_last_change', models.DateField(auto_now=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('product_name',),
            },
        ),
    ]
